v1.2.1
Quit Simple Gateway at every logout. Remove .CleanUpInstall logic.

diff --git a/Resources/XcodeProject/Remote Acccess/Resources/script b/Resources/XcodeProject/Remote Acccess/Resources/script
--- a/Resources/XcodeProject/Remote Acccess/Resources/script
+++ b/Resources/XcodeProject/Remote Acccess/Resources/script
@@ -1,6 +1,6 @@
 #!/bin/zsh
 
-#v.1.2
+#v.1.2.1
 
 #change current working directory to script location
 CWD="$(dirname "$0")"
@@ -21,10 +21,11 @@ logName=`/usr/libexec/PlistBuddy -c "Print :CFBundleName" "../Info.plist"`.log
 installVers="offline"
 
 #---These variables are concatenations of above or required information gathering
-#consoleUSER/UID - find the currently logged in user in order to ensure LaunchAgent is not loaded.
-consoleUSER=`stat -f%Su /dev/console`
-consoleUID=`id -u $consoleUSER`
-#Paths:
+#Users
+	#consoleUSER/UID - find the currently logged in user in order to ensure LaunchAgent is not loaded.
+	consoleUSER=`stat -f%Su /dev/console`
+	consoleUID=`id -u $consoleUSER`
+#Paths
     #installDir - where the Remote Access Launcher app will live
     installDir="/Library/Application Support/$supportDirName"
     #appPath - full path to .app bundle
@@ -51,24 +52,40 @@ consoleUID=`id -u $consoleUSER`
     #simplehelp LaunchAgent Location
     shlaunchagentPath="/Library/LaunchAgents/$shlaunchagentLabel.plist"
 #Versions
+	#version App version
     if [ -f "../Info.plist" ]; then
         version=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "../Info.plist")
         else
         version=0
     fi
+    #versionInstalled version installed to $appPath
     if [ -f "$appPath/Contents/Info.plist" ];then
         versionInstalled=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$appPath/Contents/Info.plist")
         else
         versionInstalled=0
     fi
+    #LAversion - version of installed launchAgent
     if /usr/libexec/PlistBuddy -c "Print :Version" "$launchagentPath"; then
         LAversion=`/usr/libexec/PlistBuddy -c "Print :Version" "$launchagentPath"`
         else
         LAversion=0
     fi
-#doNotDelete used in check where app is running from and failsafe do not attempt to update
-echo $(cd "$(dirname "$0")"; pwd -P) | egrep "$installDir"
-doNotDelete=$?
+#AppInfo
+	#doNotDelete used in check where app is running from and failsafe do not attempt to update
+	echo $(cd "$(dirname "$0")"; pwd -P) | egrep "$installDir"
+	doNotDelete=$?
+	#osxwrapperSGPID last known osxwrapper PID started by Remote Access.app
+	if [ -f "$installDir/.osxwrapperSGPID" ]; then
+		osxwrapperSGPID=`cat "$installDir/.SGPID"`
+		else
+		osxwrapperSGPID=-1
+	fi
+	#osxlauncherSGPID last known osxwrapper PID started by Remote Access.app
+	if [ -f "$installDir/.osxwrapperSGPID" ]; then
+		osxlauncherSGPID=`cat "$installDir/.SGPID"`
+		else
+		osxlauncherSGPID=-1
+	fi
 
 # Functions
 #logIt- Simple Logging snipit, seems to work well.
@@ -91,7 +108,7 @@ fi
     chmod 664 "$logPath"
 }
 
-#selfInstall - install in the correct directory (will not work until SimpleLauncher Mach-O is fixed)
+#selfInstall - install in the correct directory (will not work until privilege escalation works this script must be run as root)
 function selfInstall {
     if [ $doNotDelete -eq 0 ];then
         logIt "$appName is running from $installDir/. Cannot/will not update."
@@ -130,58 +147,16 @@ function sglaunchagentCleanup {
 
 #LaunchDaemonRACleanup - Delete installer-required LuanchDaemon
 function LaunchDaemonRACleanup {
-    if [ ! -f "$installDir/.CleanUpInstall" ]; then
-        launchctl list "$launchdaemonLabel" > /dev/null 2>&1
-        loadedSG=$?
-        if [ $loadedSG = "0" ]; then
-            logIt "Remote Access LaunchDaemon loaded."
-            if [ -f "$launchdaemonPath" ]; then
-                logIt "Remote Access LaunchDaemon found."
-                logIt "Unload Remote Access LaunchDaemon."
-                launchctl unload "$launchdaemonPath"
-                logIt "Delete Remote Access LaunchDaemon."
-                rm "$launchdaemonPath"
-                else
-                logIt "Remote Access LaunchDaemon found."
-                logIt "Remove Remote Access LaunchDaemon."
-                launchctl remove "$launchdaemonLabel"
-            fi
-        fi
-    else
-    logIt "Remove $installDir/.CleanUpInstall"
-    rm  "$installDir/.CleanUpInstall"
+    if [ -f "$installDir/.CleanUpInstall" ]; then
+    	logIt "Remove $installDir/.CleanUpInstall"
+    	rm  "$installDir/.CleanUpInstall"
+    fi
+    if [ -f "$launchdaemonPath" ]; then
+    	logIt "Remove $launchdaemonPath"
+    	rm "$launchdaemonPath"
     fi
     }
 
-#killrootSG - this kills any SimpleGateway running as root. *Should* only encounter after install at login window
-function killrootSG {
-    logIt "Checking for SimpleGateway running as root. In case we're at loginwindow."
-    PROC=( `pgrep -d \  -u root osxwrapper`)  #spacing is correct
-    for i in ${PROC[*]}; do
-        ps -o command= $i | egrep "$SGpath51|$SGpath52" > /dev/null 2>&1
-        isSG=$?
-        if [ $isSG = "0" ]; then
-            logIt "osxwrapper with PID $i is SimpleGateway running as root."
-            logIt "kill $i"
-            kill $i
-            else
-            logIt "No osxwrapper/SimpleGateway running as root"
-        fi
-    done
-    PROC=( `pgrep -d \  -u root osxlauncher`) #spacing is correct
-    for i in ${PROC[*]}; do
-        ps -o command= $i | egrep "$SGpath51|$SGpath52" > /dev/null 2>&1
-        isSG=$?
-        if [ $isSG = "0" ]; then
-            logIt "osxlauncher with PID $i is SimpleGateway running as root."
-            logIt "kill $i"
-            kill $i
-            else
-            logIt "No osxlauncher/SimpleGateway running as root"
-        fi
-    done
-    }
-    
 #LaunchAgentRA - test if our LaunchAgent exists, if not create it.
 function LaunchAgentRA {
     if [ `echo $version | sed -e 's/\.//g'` -gt `echo $LAversion | sed -e 's/\.//g'` ]; then
@@ -193,8 +168,8 @@ function LaunchAgentRA {
         defaults write "$launchagentPath" ProgramArguments -array "$appPath/Contents/MacOS/$machName"
         defaults delete "$launchagentPath" WorkingDirectory
         defaults write "$launchagentPath" AbandonProcessGroup -bool TRUE
-        defaults write "$launchagentPath" StandardErrorPath "$logDir/$appName""ERR.log"
-        defaults write "$launchagentPath" StandardOutPath "$logDir/$appName""STD.log"
+        defaults write "$launchagentPath" StandardErrorPath "$logDir/$machName""ERR.log"
+        defaults write "$launchagentPath" StandardOutPath "$logDir/$machName""STD.log"
         defaults write "$launchagentPath" Version "$version"
         chown root:wheel "$launchagentPath"
         chmod 644 "$launchagentPath"
@@ -228,37 +203,36 @@ function killUserSG {
         done
     fi
     }
-    
-#testRootSG - If SimpleGateway is running as osxwrapper or osxlauncher as root, if so it really should be us, exit 0.
-function testRootSG {
-    logIt "Testing for SimpleGateway running as root."
-    PROC=( `pgrep -d \  -u root osxlauncher`)  #spacing is correct
-    for i in ${PROC[*]}; do
-        ps -o command= $i | egrep "$SGpath51|$SGpath52" > /dev/null 2>&1
-        isSG=$?
-        
-        if [ $isSG = "0" ]; then
-            logIt "osxlauncher with PID $i is SimpleGateway and running as root - exiting."
-            logIt "---- $appName v.$version exit 0 ----"
-            exit 0
-        fi
-    done
-    
-    PROC=( `pgrep -d \  -u root osxwrapper`)  #spacing is correct
-    for i in ${PROC[*]}; do
-        
-        ps -o command= $i | egrep "$SGpath51|$SGpath52" > /dev/null 2>&1
-        isSG=$?
-        
-        if [ $isSG = "0" ]; then
-            logIt "osxwrapper with PID $i is SimpleGateway and running as root - exiting."
-            logIt "---- $appName v.$version exit 0 ----"
-            exit 0
-        fi
-    done
-    logIt "SimpleGatway not running as osxwrapper/osxlauncher as root."
+
+#killrootSG - this kills any SimpleGateway running as root. *Should* only encounter after install at login window
+function killrootSG {
+    	logIt "Killing all root SimpleGateway."
+    	PROC=( `pgrep -d \  -u root osxwrapper`)  #spacing is correct
+    	for i in ${PROC[*]}; do
+    	    ps -o command= $i | egrep "$SGpath51|$SGpath52" > /dev/null 2>&1
+    	    isSG=$?
+    	    if [ $isSG = "0" ]; then
+    	        logIt "osxwrapper with PID $i is SimpleGateway running as root."
+    	        logIt "kill $i"
+    	        kill $i
+    	        else
+    	        logIt "No osxwrapper/SimpleGateway running as root"
+    	    fi
+    	done
+    	PROC=( `pgrep -d \  -u root osxlauncher`) #spacing is correct
+    	for i in ${PROC[*]}; do
+    	    ps -o command= $i | egrep "$SGpath51|$SGpath52" > /dev/null 2>&1
+    	    isSG=$?
+    	    if [ $isSG = "0" ]; then
+    	        logIt "osxlauncher with PID $i is SimpleGateway running as root."
+    	        logIt "kill $i"
+    	        kill $i
+    	        else
+    	        logIt "No osxlauncher/SimpleGateway running as root"
+    	    fi
+    	done
     }
-    
+       
 # deploySG checks that SimpleHelp Gateway is installed and this app version is up to date, if either are not true we attempt a full reinstall
 function deploySG {
     if [ ! -d "/Library/Application Support/JWrapper-Remote Access/JWAppsSharedConfig/SimpleGatewayService" ]; then
@@ -327,13 +301,21 @@ function deploySG {
     }
 
 #startSG - start SimpleGateway backgrounded depending on version 5.1.x or 5.2
-function startSG {
-    testRootSG
-    
+function startSG {    
     if [ ! -d "/Library/Application Support/JWrapper-Remote Access/JWAppsSharedConfig/SimpleGatewayService" ];then
         logIt "SimpleHelp Gateway is not installed."
         logIt "---- $appName v.$version exit 1 ----"
         exit 1
+    fi
+        
+    if kill -0 $osxwrapperSGPID; then
+    	ps -o command= $osxwrapperSGPID | egrep "$SGpath51|$SGpath52" > /dev/null 2>&1
+        isSG=$?
+        if [ $isSG = 0 ]; then
+    	logIt "killing last known PID $osxwrapperSGPID"
+    	kill $osxwrapperSGPID
+    	sleep 5
+    	fi
     fi
     
     logIt "Starting SimpleGateway as `whoami`"
@@ -343,25 +325,41 @@ function startSG {
     [ -f "./SimpleGatewayService.app/Contents/MacOS/osxwrapper" ] && "./SimpleGatewayService.app/Contents/MacOS/osxwrapper" > /dev/null 2>&1 &
     
     sleep 1
+
+    }
+    
+#testRootSG - If SimpleGateway is running as osxwrapper or osxlauncher as root, if so it really should be us, exit 0.
+function testRootSG {
+    logIt "Testing for SimpleGateway running as root."
     
     PROC=( `pgrep -d \  -u root osxwrapper`)  #spacing is correct
     for i in ${PROC[*]}; do
+        
         ps -o command= $i | egrep "$SGpath51|$SGpath52" > /dev/null 2>&1
         isSG=$?
+        
         if [ $isSG = "0" ]; then
-            
-            logIt "Remote Access osxwrapper with PID $i is as root."
+            logIt "osxwrapper with PID $i is SimpleGateway and running as root - exiting."
             logIt "---- $appName v.$version exit 0 ----"
+            echo $i > "$installDir/.osxwrapperSGPID"
             exit 0
-            else
-            logIt "Remote Access osxwrapper not detected as running or not detected as running as root."
-            logIt "---- $appName v.$version exit 1 ----"
-            exit 1
         fi
     done
-    logIt "Remote Access osxwrapper not detected as running or not detected as running as root."
-    logIt "---- $appName v.$version exit 1 ----"
-    exit 1
+    
+        PROC=( `pgrep -d \  -u root osxlauncher`)  #spacing is correct
+    for i in ${PROC[*]}; do
+        ps -o command= $i | egrep "$SGpath51|$SGpath52" > /dev/null 2>&1
+        isSG=$?
+        
+        if [ $isSG = "0" ]; then
+            logIt "osxlauncher with PID $i is SimpleGateway and running as root - exiting."
+            logIt "---- $appName v.$version exit 0 ----"
+            echo $i > "$installDir/.osxlauncherSGPID"
+            exit 0
+        fi
+    done
+    
+    logIt "SimpleGatway not running as osxwrapper/osxlauncher as root."
     }
     
 #----Main----
@@ -370,24 +368,24 @@ initializeLogging
 # startLogging
 logIt "---- $appName v.$version start ----"
 logIt "Current working directory is $CWD."
-#selfInstall - install in the correct directory
-selfInstall
+#selfInstall - install in the correct directory (to be reenabled when privilege escalation works)
+#selfInstall
 # Installs Remote Access LaunchAgent (kind of the whole point of this.)
 LaunchAgentRA
 # Test for Simple Gateway and Remote Access.app, deploy if not present
 deploySG
 # Ensure SimpleGatway LaunchAgent is not installed or running
 sglaunchagentCleanup
-#kill root SimpleGateway at login window
-killrootSG
 # ensure SimpleGateway is not running as user
 killUserSG
 #cleanup after installer
 LaunchDaemonRACleanup
+# killrootSG kill all osxwrapper and osxlauncher
+killrootSG
 # startSG makes sure Simple Gateway is running as root if so ends the script
 #   Starts Simple Gateway as root regardless of v5.1.x or v5.2.x
 startSG
-
-
-logIt "---- $appName v.$version exit 0----"
-exit 0
+# testRootSG
+testRootSG
+logIt "---- $appName v.$version End of Script exit 1 ----"
+exit 1
